version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    container_name: simple-sinatra-service
    image: simple-sinatra-service-dev:0.0.1
    tty: true
    stdin_open: true
    volumes:
      - .:/app:delegated
      - bundle:/bundle
    ports: 
      - 80:3000

volumes: 
  bundle:
